// CATEGORIES
export const LOAD_CATEGORIES = 'LOAD_CATEGORIES';
export const REQUEST_CATEGORIES = 'REQUEST_CATEGORIES';

export const REQUEST_ADD_CATEGORIES = 'REQUEST_ADD_CATEGORIES';
export const ADD_CATEGORY = 'ADD_CATEGORY';

export const GET_CATEGORY_BY_ID_REQUEST = 'GET_CATEGORY_BY_ID_REQUEST';
export const GET_CATEGORY_BY_ID_SUCCESS = 'GET_CATEGORY_BY_ID_SUCCESS';
export const GET_CATEGORY_BY_ID_ERROR = 'GET_CATEGORY_BY_ID_ERROR';

export const UPDATE_CATEGORY_REQUEST = 'UPDATE_CATEGORY_REQUEST';
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_ERROR = 'UPDATE_CATEGORY_ERROR';

// PRODUCTS
export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';

export const GET_PRODUCT_BY_ID_REQUEST = 'GET_PRODUCT_BY_ID_REQUEST';
export const GET_PRODUCT_BY_ID_SUCCESS = 'GET_PRODUCT_BY_ID_SUCCESS';
export const GET_PRODUCT_BY_ID_ERROR = 'GET_PRODUCT_BY_ID_ERROR';

export const ADD_PRODUCT_REQUEST = 'ADD_PRODUCT_REQUEST';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR';

export const UPLOAD_MAIN_IMG_REQUEST = 'UPLOAD_MAIN_IMG_REQUEST';
export const UPLOAD_MAIN_IMG_SUCCESS = 'UPLOAD_MAIN_IMG_SUCCESS';
export const UPLOAD_MAIN_IMG_ERROR = 'UPLOAD_MAIN_IMG_ERROR';

export const DELETE_IMAGE_REQUEST = 'DELETE_IMAGE_REQUEST';
export const DELETE_IMAGE_SUCCESS = 'DELETE_IMAGE_SUCCESS';
export const DELETE_IMAGE_ERROR = 'DELETE_IMAGE_ERROR';

export const UPDATE_PRODUCT_REQUEST = 'UPDATE_PRODUCT_REQUEST';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_ERROR = 'UPDATE_PRODUCT_ERROR';

export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_ERROR = 'DELETE_PRODUCT_ERROR';

// USERS
export const LOAD_USERS = 'LOAD_USERS';
export const REQUEST_USERS = 'REQUEST_USERS';
export const ADD_USER = 'ADD_USER';
export const DELETE_USER = 'DELETE_USER';

// SETTINGS
export const REQUEST_SETTINGS = 'REQUEST_SETTINGS';
export const LOAD_SETTINGS = 'LOAD_SETTINGS';
export const REQUEST_UPDATE_SETTINGS = 'REQUEST_UPDATE_SETTINGS';
export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';

// SNACKBAR
export const SUCCESS_SNACKBAR = 'SUCCESS_SNACKBAR';
export const FAIL_SNACKBAR = 'FAIL_SNACKBAR';
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';

// THEME
export const SWITCH_DARK_MODE = 'SWITCH_MODE';
