export const LOAD_CATEGORIES = 'LOAD_CATEGORIES';
export const REQUEST_CATEGORIES = 'REQUEST_CATEGORIES';

export const REQUEST_ADD_CATEGORIES = 'REQUEST_ADD_CATEGORIES';
export const ADD_CATEGORY = 'ADD_CATEGORY';

export const LOAD_PRODUCTS = 'LOAD_PRODUCTS';
export const REQUEST_PRODUCTS = 'REQUEST_PRODUCTS';

export const SWITCH_DARK_MODE = 'SWITCH_MODE';
// Settings
export const REQUEST_SETTINGS = 'REQUEST_SETTINGS';
export const LOAD_SETTINGS = 'LOAD_SETTINGS';
export const REQUEST_UPDATE_SETTINGS = 'REQUEST_UPDATE_SETTINGS';
export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';
// SnackBar
export const SUCCESS_SNACKBAR = 'SUCCESS_SNACKBAR';
export const FAIL_SNACKBAR = 'FAIL_SNACKBAR';
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';
